### ISSUE TITLE
Custom: Unable to start otto dev with custom Vagrantfile under Windows 7 with Cygwin

### ISSUE THREAD

**Issue by mbunge** [hashicorp/otto#158]
It was not possible to run successfull `otto dev` after `otto compile` with folling Appfile:

```hcl
application {
    name = "otto-php-example"
    type = "custom"
}

customization "dev" {
    vagrant = "./Vagrantfile"
}

customization "dev-dep" {
    vagrant = "./Vagrantfile"
}
```

CLI Output

```
$ otto compile
←[0m←[1m==> Loading Appfile...←[0m
←[0m←[1m==> Fetching all Appfile dependencies...←[0m
←[0m←[1m==> Compiling...←[0m
←[0m    Application:    otto-php-example (custom)←[0m
←[0m    Project:        ottoPhpExample←[0m
←[0m    Infrastructure: aws (simple)←[0m
←[0m←[0m
←[0m    Compiling infra...←[0m
←[0m    Compiling foundation: consul←[0m
←[0m←[1m==> Compiling main application...←[0m
←[0m←[32m←[1m==> ←[32mCompilation success!←[0m
←[0m←[32m    ←[32mThis means that Otto is now ready to start a development environment,
    deploy this application, build the supporting infastructure, and
    more. See the help for more information.

    Supporting files to enable Otto to manage your application from
    development to deployment have been placed in the output directory.
    These files can be manually inspected to determine what Otto will do.←[0m

mbunge@ZOMBIEFABRIK /C/wamp/www/projects/ottoPhpExample (master)
$ otto dev
←[0;31mError building dev environment: Otto can't build a development environment for this because the
"vagrant" setting hasn't been set in the "dev" or "dev-dep" customization.

For the "custom" application type, customizations must be used to
tell Otto what to do. For the dev command, Otto requires either
the "dev" or "dev-dep" customization to be set with the "vagrant" setting.
The "vagrant" setting depends on which customization is being set. Please
refer to the documentation for more details.

Example:

    customization "dev" {
        vagrant = "path/to/Vagrantfile"
    }←[0m
```

**Comment by justincampbell** [comment]
@mbunge Does it work with `vagrantfile` instead of `vagrant`? This error message was just fixed in #135

**Comment by girishpandit88** [comment]
I can confirm, I'm also still seeing this issue. The otto compile doesn't create dev folder under .otto/ compiled section. I was trying on OSX 10.11. Originally this issue was mentioned here https://github.com/hashicorp/otto/issues/106

**Comment by ilkka** [comment]
I can't for the life of me find the bit in the custom package where the `Vagrantfile` is actually written into `.otto/app/dev` where it is expected to be found. Also, `processDev` for the custom type checks for "vagrant", not "vagrantfile", but this doesn't in fact cause an error in the compile stage. Having changed that and made a slight addition to `compileCustomDev`, I got things working. It's probably still at the "silly hack" stage but I'll submit a PR anyway.

**Comment by jrnt30** [comment]
@justincampbell Per #168 the parameter that is actually bound to in `builtin/app/custom/customization.go` is "vagrant" in the compileCustomDev callback currently, however when doing so the Vagrantfile will then not be properly rendered, as the `dev_vagrant_path` is never set.  In fact, the "vagrant" or "vagrantfile" attribute from the "dev" customization seems to be unused for anything meaningful. In the current state, unless you define a "dev-dep.vagrantfile" the target will not work at all (due to binding inconsistency) and no Vagrantfile being rendered. 

It is unclear to me however what the intended functionality is here.  In the `builtin/app/custom/data/dev/Vagrantfile.tpl` there is a binding to the `fragment_path` which is set via the `filepath.Join(ctx.Dir, "dev-dep", "Vagrantfile.fragment")` which will get populated with the contents of the "dev-dep" "vagrantfile" customization.  If the intention is to allow a set of Vagrant fragments to be dropped in 

Is the idea with Custom that there will be a rendered fragment that will act as a drop in for both Dev and Dev-Dep?  I haven't dived into the build/compile stuff for Packer yet with this until I got a better understanding of what the intention was.

**Comment by jrnt30** [comment]
I also think that #106 and #173 are all the same issue. And #142 could be resolved potentially.  One thing to note is with the inline script present in the Vagrant template file, there is an assumption that it's Debian system (apt-get) which should be stated or changed.

**Comment by mbunge** [comment]
@justincampbell it Doesn't work with vagrant and vagrantfile. The vagrantfile doesn't work when I call it directly with vagrant. 

I got the Same issue under Ubuntu 15.04.

I use virtualbox 5 on Windows and virtualbox 4.3.26 on Ubuntu.

**Comment by vlam-trulia** [comment]
If anyone is on otto 0.2 and is encountering this error while developing using an Appfile from 0.1.2, note that there was a schema change which hasn't made it to all documentation yet:

https://ottoproject.io/docs/apps/custom/customization.html

```
application {
  name = "myapplication"
  type = "custom"
}

customization {
  dev_vagrantfile = "./Vagrantfile"
}
```

**Comment by actuosus** [comment]
@vlam-trulia, thanks.

**Comment by mbunge** [comment]
@vlam-trulia thanks 😊
